/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.xd.segurit;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int action_forgot_password=0x7f080007;
        public static final int email=0x7f080003;
        public static final int login=0x7f080005;
        public static final int login_form=0x7f080002;
        public static final int login_status=0x7f080000;
        public static final int login_status_message=0x7f080001;
        public static final int password=0x7f080004;
        public static final int sign_in_button=0x7f080006;
    }
    public static final class layout {
        public static final int activity_login=0x7f030000;
    }
    public static final class menu {
        public static final int login=0x7f070000;
    }
    public static final class string {
        public static final int action_forgot_password=0x7f050006;
        public static final int action_sign_in_register=0x7f050004;
        public static final int action_sign_in_short=0x7f050005;
        public static final int app_name=0x7f050000;
        public static final int error_field_required=0x7f05000b;
        public static final int error_incorrect_password=0x7f05000a;
        public static final int error_invalid_email=0x7f050008;
        public static final int error_invalid_password=0x7f050009;
        public static final int login_progress_signing_in=0x7f050007;
        /**  Strings related to login 
         */
        public static final int prompt_email=0x7f050002;
        public static final int prompt_password=0x7f050003;
        public static final int title_activity_login=0x7f050001;
    }
    public static final class style {
        public static final int LoginFormContainer=0x7f060000;
    }
    public static final class xml {
        public static final int config=0x7f040000;
    }
}
